server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service-route
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**, /api/requests/**, /api/admin/**

        - id: user-profile-service-route
          uri: lb://USER-PROFILE-SERVICE
          predicates:
            - Path=/api/profiles/**

eureka:
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        # "gateway" ve "health" endpoint'lerini dışarıya aç
        include: "gateway,health"
