server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        # 1. Rota: Auth Service
        - id: auth-service-route
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**, /api/requests/**, /api/admin/**

        # 2. Rota: User Profile Service
        - id: user-profile-service-route
          uri: lb://USER-PROFILE-SERVICE
          predicates:
            - Path=/api/profiles/**

        # 3. Rota: Club Service
        - id: club-service-route
          uri: lb://club-service
          predicates:
            - Path=/api/clubs/**

        # 4. Rota: Event Service
        - id: event-service-route
          uri: lb://event-service
          predicates:
            - Path=/api/events/**

        # 5. Rota: Registration Service
        - id: registration-service-route
          uri: lb://registration-service
          predicates:
            - Path=/api/registrations/**

        # 6. Rota: Notification Service
        - id: notification-service-route
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**

        # 7. Rota: Post Service
        - id: post-service-route
          uri: lb://post-service
          predicates:
            - Path=/api/posts/**

        # 8. Rota: Interaction Service
        - id: interaction-service-route
          uri: lb://interaction-service
          predicates:
            - Path=/api/interactions/**

eureka:
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        # "gateway" ve "health" endpoint'lerini dışarıya aç
        include: "gateway,health"
