# auth-service.yml
server:
  port: 9001

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/uniclub_db

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: auth_schema

  rabbitmq:
    host: localhost
    port: 5672

auth:
  rabbitmq:
    exchange: "user_exchange"
    routing-key: "user.created.key"

jwt:
  secret: "bmljZS1zZWNyZXQtZm9yLXVuaWNsdWItY29ubmVjdC1wcm9qZWN0LXdpdGgtZW5vdWdoLWJ5dGVzLWZvci1oczUxMg=="
  access-token-expiration-ms: 3600000
  refresh-token-expiration-ms: 604800000
