# Interaction Service Configuration File
server:
  port: 9008

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/uniclub_db

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: interaction_schema

# JWT (Diğer servislerle aynı)
jwt:
  secret: "bmljZS1zZWNyZXQtZm9yLXVuaWNsdWItY29ubmVjdC1wcm9qZWN0LXdpdGgtZW5vdWdoLWJ5dGVzLWZvci1oczUxMg=="
  access-token-expiration-ms: 3600000
  refresh-token-expiration-ms: 604800000
