server:
  port: 9005

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/uniclub_db
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: registration_schema

  # Redis Ayarları
  data:
    redis:
      host: localhost
      port: 6379

# RabbitMQ
rabbitmq:
  exchange:
    name: "notification_exchange"
  routingkey:
    ticket_created: "ticket.created.key"

# JWT
jwt:
  secret: "bmljZS1zZWNyZXQtZm9yLXVuaWNsdWItY29ubmVjdC1wcm9qZWN0LXdpdGgtZW5vdWdoLWJ5dGVzLWZvci1oczUxMg=="
